export const BLOGSTOPIC_LOADING = 'BLOGSTOPIC_LOADING';
export const ADD_BLOGSTOPIC = 'ADD_BLOGSTOPIC';
export const BLOGSTOPIC_FAILED = 'BLOGSTOPIC_FAILED';

export const LEADERS_LOADING = 'LEADERS_LOADING';
export const ADD_LEADERS = 'ADD_LEADERS';
export const LEADERS_FAILED = 'LEADERS_FAILED';

export const PROMOS_LOADING = 'PROMOS_LOADING';
export const ADD_PROMOS = 'ADD_PROMOS';
export const PROMOS_FAILED = 'PROMOS_FAILED';

export const BLOG_LOADING = 'BLOG_LOADING';
export const ADD_BLOG = 'ADD_BLOG';
export const BLOG_FAILED = 'BLOG_FAILED';

export const TOPICS_LOADING = 'TOPICS_LOADING';
export const ADD_TOPICS = 'ADD_TOPICS';
export const TOPICS_FAILED = 'TOPICS_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';